#  Pytorch

## Introduction to Pytorch


In [132]:
import torch
import numpy as np



###  tensor basics 


* creation de tensors

In [133]:
print(torch.ones(5))
# traquer le gradiant
print(torch.ones(5, requires_grad=True))

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], requires_grad=True)


* tensor  1 dimension

In [134]:

# tensor 1 dimension 1xx1
x = torch.empty(1)
print("x:",x)
print("x.size():", x.size())

# tensor 1 dimensions 1x2
y = torch.empty(2)
print("y:",y)
print("y.size():", y.size())

# tensor 1 dimensions 1x3
z = torch.empty(3)
print("z:",z)
print("z.size():", z.size())




x: tensor([0.])
x.size(): torch.Size([1])
y: tensor([0.0000, 1.8750])
y.size(): torch.Size([2])
z: tensor([ 1.4013e-45,  0.0000e+00, -2.3569e+27])
z.size(): torch.Size([3])


* tensor 32 dimensions

In [135]:

# tensor 2 dimension 2x2
x = torch.empty(2, 2)
print("x:",x)
print("x.size():", x.size())

# tensor 2 dimensions 4x4
y = torch.empty(4,4)
print("y:",y)
print("y.size():", y.size())

# tensor 2 dimensions 8x8
z = torch.empty(8,8)
print("z:",z)
print("z.size():", z.size())




x: tensor([[9.2196e-41, 1.8980e+01],
        [0.0000e+00, 0.0000e+00]])
x.size(): torch.Size([2, 2])
y: tensor([[8.4490e-39, 1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39, 9.2755e-39]])
y.size(): torch.Size([4, 4])
z: tensor([[4.7429e+30, 1.2332e+01, 1.0897e+27, 5.8148e+25, 6.0991e+31, 4.2964e+24,
         8.3692e-01, 1.1431e+27],
        [7.1428e+31, 1.2915e+10, 5.8619e+13, 7.2436e+22, 7.3972e+31, 4.7429e+30,
         3.0064e+00, 1.8037e+22],
        [1.5232e+31, 3.0061e+00, 1.3281e+13, 4.4166e+21, 1.0317e-08, 1.2332e+01,
         1.7658e+22, 1.0317e-08],
        [1.2328e+01, 2.0821e+32, 1.7889e+22, 1.6930e+22, 2.7907e+29, 1.2332e+01,
         1.0897e+27, 5.8148e+25],
        [6.0991e+31, 4.2964e+24, 3.3320e+03, 1.0322e-08, 8.3301e-01, 1.7859e+31,
         3.3320e+03, 2.4711e+20],
        [3.5853e+00, 3.8189e+00, 4.4721e+21, 3.0039e+00,

* Tensor 3 dimension 

In [136]:

# tensor 3 dimension 2x2x2
x = torch.empty(2, 2 ,2)
print("x:",x)
print("x.size():", x.size())

# tensor 3 dimensions 4x4x6
y = torch.empty(4,4, 6)
print("y:",y)
print("y.size():", y.size())

# tensor 3 dimensions 8x8x3
z = torch.empty(8,8 ,3)
print("z:",z)
print("z.size():", z.size())




x: tensor([[[2.6250e-09, 5.2304e+22],
         [1.7080e-07, 1.0624e+21]],

        [[5.2945e-08, 1.3434e-05],
         [3.4301e-06, 4.3722e-05]]])
x.size(): torch.Size([2, 2, 2])
y: tensor([[[2.7655e+29, 1.3225e+13, 1.5563e+28, 1.9446e+31, 1.5399e+10,
          2.4493e+20],
         [7.2701e+31, 2.7909e+29, 3.7874e+00, 1.7753e+28, 3.7881e+00,
          6.7705e+22],
         [3.0039e+00, 1.8465e+25, 2.2182e+20, 1.3211e+13, 1.8038e+28,
          1.9446e+31],
         [1.6535e+19, 1.1446e+24, 1.6488e+22, 2.8573e+32, 1.7289e+28,
          1.7036e+19]],

        [[7.0976e+22, 4.1489e-17, 4.8415e+30, 1.1837e+33, 4.8391e+30,
          1.1446e+24],
         [4.2675e+30, 7.0965e+22, 6.7899e+31, 7.5338e+28, 1.7211e+22,
          3.7562e+00],
         [2.7468e+20, 7.2728e+22, 3.8184e+00, 6.7368e+22, 1.1286e+27,
          6.4533e-10],
         [3.5464e+21, 3.0029e+00, 3.8184e+00, 1.2332e+01, 8.5700e+02,
          2.7722e+20]],

        [[1.5230e+07, 6.2416e+22, 3.3069e-09, 5.2845e+13, 7.0975e+22,


* typage

In [137]:

x = torch.empty(2, dtype=torch.float64)
x

tensor([ 6.9315e-01, 1.9763e-323], dtype=torch.float64)

* create tensor

In [138]:
a =  torch.tensor([1,2,3] )
b =  torch.tensor([4,5,6] )

a

tensor([1, 2, 3])

* addition

In [139]:
# x est un tableau de 1
# y est un tableau de 0 
x= torch.ones(2,2)
y= torch.zeros(2,2)
z= x + y 
w =torch.add(x,y)
print("z" , z)
print("w" , w)
# w == z 

z tensor([[1., 1.],
        [1., 1.]])
w tensor([[1., 1.],
        [1., 1.]])


** les methodes avec _ modifie directement la valeur de l'objet **

In [140]:

# Créer un tenseur PyTorch
x2 = torch.tensor([1, 2, 3])

# Ajouter 1 à chaque élément du tenseur
x2.add_(1)

print(x2)

tensor([2, 3, 4])


* subtraction

In [141]:
w= torch.sub(x,y )
z=x-y
print("z" , z)
print("w" , w)
# z==w



z tensor([[1., 1.],
        [1., 1.]])
w tensor([[1., 1.],
        [1., 1.]])


* multiplication

In [142]:
c = a * b
c = torch.mul(a, b)
print("c: " , c)

c:  tensor([ 4, 10, 18])


* division

In [143]:
c = a / b
c = torch.div(a, b)
print("c: " , c)

c:  tensor([0.2500, 0.4000, 0.5000])


* puissance

In [144]:
c = torch.pow(a, 3)
print("c: " , c)

c:  tensor([ 1,  8, 27])


* exponential 

In [145]:
c = torch.exp(a) 
print("c: " , c)

c:  tensor([ 2.7183,  7.3891, 20.0855])


* logarithms

In [146]:
c = torch.log(a)

print("c: " , c)

c:  tensor([0.0000, 0.6931, 1.0986])


# numpy & tensor 

In [147]:

# Créer un tableau NumPy
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convertir le tableau NumPy en tenseur PyTorch
torch_tensor = torch.from_numpy(numpy_array)


print(torch_tensor)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [148]:

# Créer un tenseur PyTorch
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Convertir le tenseur PyTorch en tableau NumPy
numpy_array = torch_tensor.numpy()

print(numpy_array)

[[1 2 3]
 [4 5 6]]


In [149]:
## types 
print("torch_tensor:" , type(numpy_array))
print("numpy_array:" , type(numpy_array))

torch_tensor: <class 'numpy.ndarray'>
numpy_array: <class 'numpy.ndarray'>


## dictionaire et tensor

In [150]:

# Créer un dictionnaire avec des paires clé-valeur
my_dict = {'a': 1, 'b': 2, 'c': 3}

# Appeler la méthode .items() sur le dictionnaire
print(my_dict.items())

dict_items([('a', 1), ('b', 2), ('c', 3)])


In [151]:

# Créer un tenseur PyTorch à 2 dimensions
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Extraire un élément du tenseur
my_element = my_tensor[1, 1]

# Appeler la méthode .items() sur l'élément (ce qui provoque une erreur)
print(my_element.item() )

5


## reshaping

In [152]:

# Créer un tenseur de dimension (2, 3)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Changer la dimension en (3, 2)
x_reshaped = x.reshape(3, 2)

print(x_reshaped)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


La méthode .view() est utilisée pour changer la forme (ou dimension) d'un tenseur PyTorch sans modifier les données sous-jacentes. Cela peut être utile lorsque vous travaillez avec des modèles de réseau de neurones qui nécessitent des tenseurs d'entrée de dimensions spécifiques.

In [153]:

# Créer un tenseur à une dimension de taille 6
x = torch.tensor([1, 2, 3, 4, 5, 6])

# Changer la dimension en (2, 3)
x_reshaped = x.view(2, 3)

print(x_reshaped)

tensor([[1, 2, 3],
        [4, 5, 6]])
